#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Unnamed1
 Dymola Version 2020x (64-bit), 2019-10-10 translated this at Tue Dec 15 14:26:36 2020

  Evaluate = true;
OutputCPUtime = true;
 */

#include <matrixop.h>
#if defined(DynSimStruct) || defined(BUILDFMU)
static double DymArrays2[5]={0.0, 0.0, 0.0, 0.0, 0.0};
static double DymArrays1[12]={2.0, 3.0, 4.0, 5.0, 6.0, 1.0, 2.0, 1.0, 0.0, 0.0, 
  0.0, 1.0};
static double DymArrays0[60]={0.2772533069, 2600000.0, 78000000.0, 130000000.0, 
  260000000.0, 124.559598, 0.3764124879, 5420.0, 163000.0, 271000.0, 542000.0, 
  91.7465854, 0.5733287467, 1.20019, 36.0, 60.0, 120.0, 60.23518036, 
  0.6949656687, 0.047379, 1.42, 2.37, 4.74, 49.69246974, 0.7231651492, 0.005496,
   0.346, 0.577, 1.15, 47.75473555, 0.7725467777, 0.00308202, 0.0925, 0.154, 
  0.308, 44.70222575, 0.8215846725, 0.000899826, 0.027, 0.045, 0.09, 42.03408561,
   0.8710953152, 0.000279265, 0.00838, 0.014, 0.0279, 39.64498472, 0.9705722494,
   3.21E-05, 0.000964, 0.00161, 0.00321, 35.58164833, 1.019511409, 1.2E-05, 
  0.00036, 0.0006, 0.0012, 33.87363804};
static double DymArrays3[60]={0.2772533069, 3.41E+23, 1.02E+25, 1.7E+25, 
  3.41E+25, 841.3862173, 0.3764124879, 292000000000000.0, 8.77E+15, 1.46E+16, 
  2.92E+16, 314.7117228, 0.5733287467, 269653.0, 8090000.0, 13500000.0, 
  27000000.0, 111.2161345, 0.6949656687, 989.077, 29700.0, 49500.0, 98900.0, 
  84.26536356, 0.7231651492, 100.469, 3010.0, 5020.0, 10000.0, 75.1603267, 
  0.7725467777, 12.884, 387.0, 644.0, 1290.0, 67.82518605, 0.8215846725, 2.01285,
   60.4, 101.0, 201.0, 61.81271908, 0.8710953152, 0.369514, 11.1, 18.5, 37.0, 
  56.78966726, 0.9705722494, 0.018342, 0.55, 0.917, 1.83, 48.87192858, 
  1.019511409, 0.00477279, 0.143, 0.239, 0.477, 45.69060487};
#endif
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  int  id_0member;
};
DYMOLA_STATIC struct DymStruc0 DymStruc0_construct(int   id_02) {
  struct DymStruc0 dummy_0;
  dummy_0.id_0member = id_02;
  return dummy_0;
}
/* Prototypes for functions used in model */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(
  struct DymStruc0 tableID0_0, double  timeIn0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(
  struct DymStruc0 tableID0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(
  struct DymStruc0 tableID0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableValue_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  timeIn0_0, double  
  nextTimeEvent0_0, double  prex_0nextTimeEvent);
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTimeTable_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  double  startTime0_0, IntegerArray   columns0_0, int  smoothness0_0, int  
  extrapolation0_0, double  shiftTime0_0, int  timeEvents0_0, int  
  verboseRead0_0, int id_, int alwaysMakeNew_);
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M(
  void* externalCombiTimeTable0_0);
DYMOLA_STATIC int   Modelica_Utilities_Strings_isEmpty(const char*  string0_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getNextTimeEvent
input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete input Real timeIn;
discrete output Real nextTimeEvent "Next time event in table";

external "C" nextTimeEvent = ModelicaStandardTables_CombiTimeTable_nextTimeEvent(tableID, timeIn);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getNextTimeEvent;

  */
extern double (ModelicaStandardTables_CombiTimeTable_nextTimeEvent)(void*, 
  double );
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(
  struct DymStruc0 tableID0_0, double  timeIn0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getNextTimeEvent")
  {
    /* Declare outputs and temporaries */
    double   nextTimeEvent0_0;
    nextTimeEvent0_0=0;
    /* Start of real code */
    {
      nextTimeEvent0_0 = (ModelicaStandardTables_CombiTimeTable_nextTimeEvent)(
        externalTable_[tableID0_0.id_0member].obj_, timeIn0_0);
      }
    /* Output section */
    PopContext()
    return nextTimeEvent0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableTmax
input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete output Real timeMax "Maximum abscissa value in table";

external "C" timeMax = ModelicaStandardTables_CombiTimeTable_maximumTime(tableID);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTimeTableTmax;

  */
extern double (ModelicaStandardTables_CombiTimeTable_maximumTime)(void*);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(
  struct DymStruc0 tableID0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableTmax")
  {
    /* Declare outputs and temporaries */
    double   timeMax0_0;
    timeMax0_0=0;
    /* Start of real code */
    {
      timeMax0_0 = (ModelicaStandardTables_CombiTimeTable_maximumTime)(
        externalTable_[tableID0_0.id_0member].obj_);
      }
    /* Output section */
    PopContext()
    return timeMax0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableTmin
input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete output Real timeMin "Minimum abscissa value in table";

external "C" timeMin = ModelicaStandardTables_CombiTimeTable_minimumTime(tableID);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTimeTableTmin;

  */
extern double (ModelicaStandardTables_CombiTimeTable_minimumTime)(void*);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(
  struct DymStruc0 tableID0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableTmin")
  {
    /* Declare outputs and temporaries */
    double   timeMin0_0;
    timeMin0_0=0;
    /* Start of real code */
    {
      timeMin0_0 = (ModelicaStandardTables_CombiTimeTable_minimumTime)(
        externalTable_[tableID0_0.id_0member].obj_);
      }
    /* Output section */
    PopContext()
    return timeMin0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableValue
input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
input Integer icol;
discrete input Real timeIn;
discrete input Real nextTimeEvent;
discrete input Real pre_nextTimeEvent;
discrete output Real y;

external "C" y = ModelicaStandardTables_CombiTimeTable_getValue(tableID, icol, timeIn, nextTimeEvent, pre_nextTimeEvent);
annotation(derivative(noDerivative=nextTimeEvent, noDerivative=pre_nextTimeEvent)=Modelica.Blocks.Tables.Internal.getDerTimeTableValue, Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTimeTableValue;

  */
extern double (ModelicaStandardTables_CombiTimeTable_getValue)(void*, int , 
  double , double , double );
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableValue_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  timeIn0_0, double  
  nextTimeEvent0_0, double  prex_0nextTimeEvent) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableValue")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      y0_0 = (ModelicaStandardTables_CombiTimeTable_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, timeIn0_0, nextTimeEvent0_0, 
        prex_0nextTimeEvent);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function constructor
input String tableName "Table name";
input String fileName "File name";
discrete input Real table[:, :];
discrete input Real startTime(unit = "s");
input Integer columns[:];
input Modelica.Blocks.Types.Smoothness smoothness;
input Modelica.Blocks.Types.Extrapolation extrapolation;
discrete input Real shiftTime(start = 0.0, unit = "s");
input Modelica.Blocks.Types.TimeEvents timeEvents(start = Modelica.Blocks.Types.TimeEvents.Always);
input Boolean verboseRead(start = true) "= true: Print info message; = false: No info message";
output Modelica.Blocks.Types.ExternalCombiTimeTable externalCombiTimeTable;

external "C" externalCombiTimeTable = ModelicaStandardTables_CombiTimeTable_init2(fileName, tableName, table, size(table, 1), size(table, 2), startTime, columns, size(columns, 1), smoothness, extrapolation, shiftTime, timeEvents, verboseRead);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end constructor;

  */
extern void* (ModelicaStandardTables_CombiTimeTable_init2)(const char* , 
  const char* , double  const *, size_t, size_t, double , int  const *, size_t, 
  int , int , double , int , int );
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTimeTable_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  double  startTime0_0, IntegerArray   columns0_0, int  smoothness0_0, int  
  extrapolation0_0, double  shiftTime0_0, int  timeEvents0_0, int  
  verboseRead0_0, int id_, int alwaysMakeNew_) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTimeTable")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  externalCombiTimeTable0_0;
    externalCombiTimeTable0_0.id_0member=0;
    /* Start of real code */
    {
      externalCombiTimeTable0_0.id_0member=id_;
      if (externalTable_[id_].destructor_ && externalTable_[id_].obj_ && alwaysMakeNew_) {
      void*x_=externalTable_[id_].obj_;
      externalTable_[id_].obj_=0;
      (*(externalTable_[id_].destructor_))(x_);
      } else if (!externalTable_[id_].destructor_) {externalTable_[id_].obj_=0;}
      #if (defined(_OPENMP) && !defined(DISABLE_DYMOLA_OPENMP))
      if (!(externalTable_[id_].haveLock_)) {omp_init_lock(&(externalTable_[id_].lockExternal_));externalTable_[id_].haveLock_=1;}
      #endif
      externalTable_[id_].destructor_=Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M;

        if (!externalTable_[id_].obj_) externalTable_[id_].obj_ = (
        ModelicaStandardTables_CombiTimeTable_init2)(fileName0_0, tableName0_0, 
        table0_0.data, table0_0.dims[1-1], table0_0.dims[2-1], startTime0_0, 
        columns0_0.data, columns0_0.dims[1-1], smoothness0_0, extrapolation0_0, 
        shiftTime0_0, timeEvents0_0, verboseRead0_0);
      }
    /* Output section */
    PopContext()
    return externalCombiTimeTable0_0;
  }}

/* Flattened Modelica model:

function destructor
input Modelica.Blocks.Types.ExternalCombiTimeTable externalCombiTimeTable;

external "C" ModelicaStandardTables_CombiTimeTable_close(externalCombiTimeTable);
annotation(Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="modelica://Modelica/Resources/Library");
end destructor;

  */
extern void (ModelicaStandardTables_CombiTimeTable_close)(void*);
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M(
  void* externalCombiTimeTable0_0) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTimeTable.destructor")
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      (ModelicaStandardTables_CombiTimeTable_close)(externalCombiTimeTable0_0);
      }
    /* Output section */
    PopContext()
    return ;
  }}

/* Flattened Modelica model:

function Modelica.Utilities.Strings.isEmpty
input String string;
output Boolean result "True, if string is empty";
protected 
Integer nextIndex;
Integer len;
public 
algorithm 
nextIndex := ModelicaStrings_skipWhiteSpace(string, 1);
len := ModelicaStrings_length(string);
if (len < 1 or nextIndex > len) then 
result := true;
else
result := false;
end if;
end Modelica.Utilities.Strings.isEmpty;

  */
DYMOLA_STATIC int   Modelica_Utilities_Strings_isEmpty(const char*  string0_0) {
  PushContext("Modelica.Utilities.Strings.isEmpty")
  {
    /* Declare outputs and temporaries */
    int   result0_0;
    int   nextIndex0_0;
    int   len0_0;
    result0_0=0;
    nextIndex0_0=0;
    len0_0=0;
    /* Start of real code */
      nextIndex0_0 = ModelicaStrings_skipWhiteSpace(string0_0, 1);
      len0_0 = ModelicaStrings_length(string0_0);
      if (len0_0 < 1 OR nextIndex0_0 > len0_0) {
        result0_0 = true;
      }
      else{
        result0_0 = false;
      }
    /* Output section */
    PopContext()
    return result0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    2
#define NW_    188
#define NP_    0
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   4
#define MAXAuxStrLen_   500
#define NHash1_ -207506602
#define NHash2_ -2037985857
#define NHash3_ 0
#define NI_    0
#define NRelF_ 2
#define NRel_  2
#define NTim_  2
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 4
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 4
#define NrDymolaTimers_ 0
#define NWhen_ 4
#define NCheckIf_ 0
#define NGlobalHelp_ 4
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 2
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Unnamed1";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/meagh/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
DYNX(Y_,0) = CurrentClockTime;
if (DYNEvent) DYNX(Y_,1) += 1;

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 5;
DYNX(W_,94) = 5;
DYNX(W_,6) = false;
memcpy(&DYNX(W_,7), &DymArrays0, sizeof(double)*60);
#endif
DYNSetAuxString(did_, "NoName", 0);
DYNSetAuxString(did_, "NoName", 1);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,67) = true;
memcpy(&DYNX(W_,68), &DymArrays1, sizeof(double)*12);
DYNX(W_,80) = false;
memcpy(&DYNX(W_,85), &DymArrays2, sizeof(double)*5);
DYNX(W_,100) = false;
memcpy(&DYNX(W_,101), &DymArrays3, sizeof(double)*60);
#endif
DYNSetAuxString(did_, "NoName", 2);
DYNSetAuxString(did_, "NoName", 3);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,161) = true;
memcpy(&DYNX(W_,162), &DymArrays1, sizeof(double)*12);
DYNX(W_,174) = false;
memcpy(&DYNX(W_,179), &DymArrays2, sizeof(double)*5);
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
InitialBoundSection
DYNX(DYNhelp,0) = (PushModelContext(1,"Modelica.Utilities.Strings.isEmpty(combiTimeTable7.fileName)")
  Modelica_Utilities_Strings_isEmpty("NoName"));
PopModelContext();
DYNX(DYNhelp,1) = divinvGuarded(DYNX(W_,75),"combiTimeTable7.timeScale");
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTimeTable((if combiTimeTable7.tableOnFile then combiTimeTable7.tableName else \"NoName\"), (if combiTimeTable7.tableOnFile and combiTimeTable7.fileName <> \"NoName\" and  not Modelica.Utilities.Strings.isEmpty(combiTimeTable7.fileName) then combiTimeTable7.fileName else \"NoName\"), combiTimeTable7.table, combiTimeTable7.startTime/combiTimeTable7.timeScale, combiTim...")
    Modelica_Blocks_Types_ExternalCombiTimeTable_M(IF DYNX(W_,6) THEN "NoName"
     ELSE "NoName", IF DYNX(W_,6) AND (strcmp("NoName", "NoName")!=0) AND  NOT 
    DYNX(DYNhelp,0) THEN "NoName" ELSE "NoName", RealTemporaryDense( &DYNX(W_,7),
     2, 10, 6), DYNX(DYNhelp,1)*DYNX(W_,77), IntegerTemporaryDense( &DYNX(W_,68),
     1, 5), (Integer)(DYNX(W_,73)), (Integer)(DYNX(W_,74)), DYNX(DYNhelp,1)*
    DYNX(W_,78), (Integer)(IF DYNX(W_,73) == 1 THEN DYNX(W_,79) ELSE IF 
    DYNX(W_,73) == 3 THEN 1 ELSE 3), (Integer)(IF DYNX(W_,6) THEN DYNX(W_,67)
     ELSE false), 0, 0));
  DYNX(W_,90) = dummy_DymStruc0.id_0member;
PopAllMarks();
}
BoundParameterSection
DYNX(W_,83) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmin(\ncombiTimeTable7.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90)))));
PopModelContext();
DYNX(W_,81) = DYNX(W_,83)*DYNX(W_,75);
DYNX(W_,84) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmax(\ncombiTimeTable7.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90)))));
PopModelContext();
DYNX(W_,82) = DYNX(W_,84)*DYNX(W_,75);
InitialBoundSection
DYNX(DYNhelp,2) = (PushModelContext(1,"Modelica.Utilities.Strings.isEmpty(combiTimeTable8.fileName)")
  Modelica_Utilities_Strings_isEmpty("NoName"));
PopModelContext();
DYNX(DYNhelp,3) = divinvGuarded(DYNX(W_,169),"combiTimeTable8.timeScale");
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTimeTable((if combiTimeTable8.tableOnFile then combiTimeTable8.tableName else \"NoName\"), (if combiTimeTable8.tableOnFile and combiTimeTable8.fileName <> \"NoName\" and  not Modelica.Utilities.Strings.isEmpty(combiTimeTable8.fileName) then combiTimeTable8.fileName else \"NoName\"), combiTimeTable8.table, combiTimeTable8.startTime/combiTimeTable8.timeScale, combiTim...")
    Modelica_Blocks_Types_ExternalCombiTimeTable_M(IF DYNX(W_,100) THEN "NoName"
     ELSE "NoName", IF DYNX(W_,100) AND (strcmp("NoName", "NoName")!=0) AND 
     NOT DYNX(DYNhelp,2) THEN "NoName" ELSE "NoName", RealTemporaryDense( 
    &DYNX(W_,101), 2, 10, 6), DYNX(DYNhelp,3)*DYNX(W_,171), IntegerTemporaryDense( 
    &DYNX(W_,162), 1, 5), (Integer)(DYNX(W_,167)), (Integer)(DYNX(W_,168)), 
    DYNX(DYNhelp,3)*DYNX(W_,172), (Integer)(IF DYNX(W_,167) == 1 THEN 
    DYNX(W_,173) ELSE IF DYNX(W_,167) == 3 THEN 1 ELSE 3), (Integer)(IF 
    DYNX(W_,100) THEN DYNX(W_,161) ELSE false), 1, 0));
  DYNX(W_,184) = dummy_DymStruc0.id_0member;
PopAllMarks();
}
BoundParameterSection
DYNX(W_,177) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmin(\ncombiTimeTable8.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184)))));
PopModelContext();
DYNX(W_,175) = DYNX(W_,177)*DYNX(W_,169);
DYNX(W_,178) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmax(\ncombiTimeTable8.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184)))));
PopModelContext();
DYNX(W_,176) = DYNX(W_,178)*DYNX(W_,169);
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,91) = 0;
DYNX(W_,92) = 0;
DYNX(W_,185) = 0;
DYNX(W_,186) = 0;
#endif
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,1) = DYNX(W_,92);
DYNX(Aux_,0) = DYNX(W_,91);
DYNX(Aux_,3) = DYNX(W_,186);
DYNX(Aux_,2) = DYNX(W_,185);
InitialSection
InitialSection2
DYNX(W_,93) = DYNTime;
InitialBoundSection
DYNX(W_,92) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\ncombiTimeTable7.tableID, \ncombiTimeTable7.timeScaled)")
  Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), DYNX(W_,93)));
PopModelContext();
InitialSection2
DYNX(W_,91) = IF Less(DYNX(W_,92),"combiTimeTable7.nextTimeEventScaled", 1E+60,
  "1E+60", 0) THEN DYNX(W_,92) ELSE 1E+60;
DYNX(W_,187) = DYNTime;
InitialBoundSection
DYNX(W_,186) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\ncombiTimeTable8.tableID, \ncombiTimeTable8.timeScaled)")
  Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), DYNX(W_,187)));
PopModelContext();
InitialSection2
DYNX(W_,185) = IF Less(DYNX(W_,186),"combiTimeTable8.nextTimeEventScaled", 1E+60,
  "1E+60", 1) THEN DYNX(W_,186) ELSE 1E+60;
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2
DYNX(W_,93) = DYNTime;
DYNX(W_,187) = DYNTime;
beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,91), 0), 0), 0) 
  DYNX(W_,92) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\ncombiTimeTable7.tableID, \ncombiTimeTable7.timeScaled)")
    Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
    (Integer)(DYNX(W_,90))), DYNX(W_,93)));
  PopModelContext();
endwhenModelica()
endwhenBlock


beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,91), 0), 0), 1) 
  DYNX(W_,91) = IF DYNX(W_,92) < 1E+60 THEN DYNX(W_,92) ELSE 1E+60;
endwhenModelica()
endwhenBlock


beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,185), 1), 1), 2) 
  DYNX(W_,186) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\ncombiTimeTable8.tableID, \ncombiTimeTable8.timeScaled)")
    Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
    (Integer)(DYNX(W_,184))), DYNX(W_,187)));
  PopModelContext();
endwhenModelica()
endwhenBlock


beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,185), 1), 1), 3) 
  DYNX(W_,185) = IF DYNX(W_,186) < 1E+60 THEN DYNX(W_,186) ELSE 1E+60;
endwhenModelica()
endwhenBlock


DYNX(W_,1) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable7.tableID, \n1, \ncombiTimeTable7.timeScaled, \ncombiTimeTable7.nextTimeEventScaled, \npre(combiTimeTable7.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), 1, DYNX(W_,93), DYNX(W_,92), PRE(DYNX(W_,92), 2)));
PopModelContext();
DYNX(W_,2) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable7.tableID, \n2, \ncombiTimeTable7.timeScaled, \ncombiTimeTable7.nextTimeEventScaled, \npre(combiTimeTable7.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), 2, DYNX(W_,93), DYNX(W_,92), PRE(DYNX(W_,92), 2)));
PopModelContext();
DYNX(W_,3) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable7.tableID, \n3, \ncombiTimeTable7.timeScaled, \ncombiTimeTable7.nextTimeEventScaled, \npre(combiTimeTable7.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), 3, DYNX(W_,93), DYNX(W_,92), PRE(DYNX(W_,92), 2)));
PopModelContext();
DYNX(W_,4) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable7.tableID, \n4, \ncombiTimeTable7.timeScaled, \ncombiTimeTable7.nextTimeEventScaled, \npre(combiTimeTable7.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), 4, DYNX(W_,93), DYNX(W_,92), PRE(DYNX(W_,92), 2)));
PopModelContext();
DYNX(W_,5) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable7.tableID, \n5, \ncombiTimeTable7.timeScaled, \ncombiTimeTable7.nextTimeEventScaled, \npre(combiTimeTable7.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,90))), 5, DYNX(W_,93), DYNX(W_,92), PRE(DYNX(W_,92), 2)));
PopModelContext();
DYNX(W_,95) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable8.tableID, \n1, \ncombiTimeTable8.timeScaled, \ncombiTimeTable8.nextTimeEventScaled, \npre(combiTimeTable8.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), 1, DYNX(W_,187), DYNX(W_,186), PRE(DYNX(W_,186), 3)));
PopModelContext();
DYNX(W_,96) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable8.tableID, \n2, \ncombiTimeTable8.timeScaled, \ncombiTimeTable8.nextTimeEventScaled, \npre(combiTimeTable8.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), 2, DYNX(W_,187), DYNX(W_,186), PRE(DYNX(W_,186), 3)));
PopModelContext();
DYNX(W_,97) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable8.tableID, \n3, \ncombiTimeTable8.timeScaled, \ncombiTimeTable8.nextTimeEventScaled, \npre(combiTimeTable8.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), 3, DYNX(W_,187), DYNX(W_,186), PRE(DYNX(W_,186), 3)));
PopModelContext();
DYNX(W_,98) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable8.tableID, \n4, \ncombiTimeTable8.timeScaled, \ncombiTimeTable8.nextTimeEventScaled, \npre(combiTimeTable8.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), 4, DYNX(W_,187), DYNX(W_,186), PRE(DYNX(W_,186), 3)));
PopModelContext();
DYNX(W_,99) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValue(\ncombiTimeTable8.tableID, \n5, \ncombiTimeTable8.timeScaled, \ncombiTimeTable8.nextTimeEventScaled, \npre(combiTimeTable8.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,184))), 5, DYNX(W_,187), DYNX(W_,186), PRE(DYNX(W_,186), 3)));
PopModelContext();

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("combiTimeTable7.nout", "Number of outputs [:#(type=Integer)]", 5,\
 1.0,1E+100,0.0,0,517)
DeclareVariable("combiTimeTable7.y[1]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable7.y[2]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable7.y[3]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable7.y[4]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable7.y[5]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable7.tableOnFile", "= true, if table is defined on file or in function usertab [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable7.table[1, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.2772533069, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[1, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 2600000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[1, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 78000000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[1, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 130000000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[1, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 260000000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[1, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 124.559598, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.3764124879, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 5420.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 163000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 271000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 542000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[2, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 91.7465854, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.5733287467, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.20019, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 36.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 60.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 120.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[3, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 60.23518036, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.6949656687, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.047379, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.42, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 2.37, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 4.74, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[4, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 49.69246974, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.7231651492, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.005496, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.346, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.577, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.15, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[5, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 47.75473555, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.7725467777, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00308202, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.0925, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.154, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.308, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[6, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 44.70222575, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.8215846725, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.000899826, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.027, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.045, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.09, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[7, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 42.03408561, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.8710953152, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.000279265, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00838, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.014, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.0279, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[8, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 39.64498472, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.9705722494, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 3.21E-05, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.000964, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00161, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00321, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[9, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 35.58164833, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.019511409, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.2E-05, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00036, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.0006, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.0012, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.table[10, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 33.87363804, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.verboseRead", "= true, if info message that file is loading is to be printed [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable7.columns[1]", "Columns of table to be interpolated [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable7.columns[2]", "Columns of table to be interpolated [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable7.columns[3]", "Columns of table to be interpolated [:#(type=Integer)]",\
 4, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable7.columns[4]", "Columns of table to be interpolated [:#(type=Integer)]",\
 5, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable7.columns[5]", "Columns of table to be interpolated [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable7.smoothness", "Smoothness of table interpolation [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 1, 1.0,5.0,0.0,0,517)
DeclareVariable("combiTimeTable7.extrapolation", "Extrapolation of data outside the definition range [:#(type=Modelica.Blocks.Types.Extrapolation)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("combiTimeTable7.timeScale", "Time scale of first table column [s]",\
 1, 1E-15,1E+100,0.0,0,513)
DeclareVariable("combiTimeTable7.offset[1]", "Offsets of output signals", 0, \
0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.startTime", "Output = offset for time < startTime [s]",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.shiftTime", "Shift time of first table column [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.timeEvents", "Time event handling of table interpolation [:#(type=Modelica.Blocks.Types.TimeEvents)]",\
 1, 1.0,3.0,0.0,0,517)
DeclareVariable("combiTimeTable7.verboseExtrapolation", "= true, if warning messages are to be printed if time is outside the table definition range [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable7.t_min", "Minimum abscissa value defined in table [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.t_max", "Maximum abscissa value defined in table [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.t_minScaled", "Minimum (scaled) abscissa value defined in table [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.t_maxScaled", "Maximum (scaled) abscissa value defined in table [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable7.p_offset[1]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable7.p_offset[2]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable7.p_offset[3]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable7.p_offset[4]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable7.p_offset[5]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable7.tableID.id", "[:#(type=Integer)]", 0, 0.0,0.0,\
0.0,0,2565)
DeclareVariable("combiTimeTable7.nextTimeEvent", "Next time event instant [s]", 0,\
 0.0,0.0,0.0,0,2704)
DeclareVariable("combiTimeTable7.nextTimeEventScaled", "Next scaled time event instant [1]",\
 0, 0.0,0.0,0.0,0,2704)
DeclareVariable("combiTimeTable7.timeScaled", "Scaled time [1]", 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareVariable("combiTimeTable8.nout", "Number of outputs [:#(type=Integer)]", 5,\
 1.0,1E+100,0.0,0,517)
DeclareVariable("combiTimeTable8.y[1]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable8.y[2]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable8.y[3]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable8.y[4]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable8.y[5]", "Connector of Real output signals", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("combiTimeTable8.tableOnFile", "= true, if table is defined on file or in function usertab [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable8.table[1, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.2772533069, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[1, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 3.41E+23, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[1, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.02E+25, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[1, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.7E+25, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[1, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 3.41E+25, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[1, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 841.3862173, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.3764124879, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 292000000000000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 8.77E+15, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.46E+16, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 2.92E+16, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[2, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 314.7117228, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.5733287467, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 269653.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 8090000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 13500000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 27000000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[3, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 111.2161345, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.6949656687, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 989.077, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 29700.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 49500.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 98900.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[4, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 84.26536356, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.7231651492, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 100.469, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 3010.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 5020.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 10000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[5, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 75.1603267, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.7725467777, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 12.884, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 387.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 644.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1290.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[6, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 67.82518605, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.8215846725, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 2.01285, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 60.4, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 101.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 201.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[7, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 61.81271908, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.8710953152, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.369514, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 11.1, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 18.5, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 37.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[8, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 56.78966726, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.9705722494, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.018342, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.55, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.917, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.83, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[9, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 48.87192858, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 1]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 1.019511409, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 2]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.00477279, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 3]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.143, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 4]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.239, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 5]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 0.477, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.table[10, 6]", "Table matrix (time = first column; e.g., table=[0, 0; 1, 1; 2, 4])",\
 45.69060487, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.verboseRead", "= true, if info message that file is loading is to be printed [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable8.columns[1]", "Columns of table to be interpolated [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable8.columns[2]", "Columns of table to be interpolated [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable8.columns[3]", "Columns of table to be interpolated [:#(type=Integer)]",\
 4, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable8.columns[4]", "Columns of table to be interpolated [:#(type=Integer)]",\
 5, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable8.columns[5]", "Columns of table to be interpolated [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,517)
DeclareVariable("combiTimeTable8.smoothness", "Smoothness of table interpolation [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 1, 1.0,5.0,0.0,0,517)
DeclareVariable("combiTimeTable8.extrapolation", "Extrapolation of data outside the definition range [:#(type=Modelica.Blocks.Types.Extrapolation)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("combiTimeTable8.timeScale", "Time scale of first table column [s]",\
 1, 1E-15,1E+100,0.0,0,513)
DeclareVariable("combiTimeTable8.offset[1]", "Offsets of output signals", 0, \
0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.startTime", "Output = offset for time < startTime [s]",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.shiftTime", "Shift time of first table column [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.timeEvents", "Time event handling of table interpolation [:#(type=Modelica.Blocks.Types.TimeEvents)]",\
 1, 1.0,3.0,0.0,0,517)
DeclareVariable("combiTimeTable8.verboseExtrapolation", "= true, if warning messages are to be printed if time is outside the table definition range [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("combiTimeTable8.t_min", "Minimum abscissa value defined in table [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.t_max", "Maximum abscissa value defined in table [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.t_minScaled", "Minimum (scaled) abscissa value defined in table [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.t_maxScaled", "Maximum (scaled) abscissa value defined in table [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("combiTimeTable8.p_offset[1]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable8.p_offset[2]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable8.p_offset[3]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable8.p_offset[4]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable8.p_offset[5]", "Offsets of output signals", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("combiTimeTable8.tableID.id", "[:#(type=Integer)]", 0, 0.0,0.0,\
0.0,0,2565)
DeclareVariable("combiTimeTable8.nextTimeEvent", "Next time event instant [s]", 0,\
 0.0,0.0,0.0,0,2704)
DeclareVariable("combiTimeTable8.nextTimeEventScaled", "Next scaled time event instant [1]",\
 0, 0.0,0.0,0.0,0,2704)
DeclareVariable("combiTimeTable8.timeScaled", "Scaled time [1]", 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareOutput("CPUtime", "[s]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("EventCounter", "", 1, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
pre(DYNX(W_,91),"combiTimeTable7.nextTimeEvent", 0, 0);
pre(DYNX(W_,92),"combiTimeTable7.nextTimeEventScaled", 0, 2);
pre(DYNX(W_,185),"combiTimeTable8.nextTimeEvent", 0, 1);
pre(DYNX(W_,186),"combiTimeTable8.nextTimeEventScaled", 0, 3);
EndPreBlock
UpdateQEvaluate(4)
EndDataBlock
